# General DAQ config setting on LabVIEW
batch_size: 1000 # int, how many events to process at a time
post_trigger: 0.875 # float, between 0 and 1
daisy_chain: True # bool
dgtz_dynamic_range_mV: 2000 # Digitizer dynamic range in mV. 2000 or 500
non_signal_channels: ['b1_ch0', 'b2_ch15'] # some channels are used for paddles, exclude them for reconstructing variables
bottom_pmt_channels: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214]
side_pmt_channels: [300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315]
row1_pmt_channels: [300, 304, 308, 312]
row2_pmt_channels: [301, 305, 309, 313]
row3_pmt_channels: [302, 306, 310, 314]
row4_pmt_channels: [303, 307, 311, 315]
ch_saturated_threshold: 0 # threshold below which a channel is considered saturated. Unit: adc

# PMT calibration file (DROP looks for this file in yaml directory)
spe_fit_results_file: 'bnl1t_spe_fit_results_220826.csv'

# Noise filter
apply_high_pass_filter: False
high_pass_cutoff_Hz: 5e6
# The following are reserved for rolling baseline subtraction (not yet implemented)
moving_avg_length: 10
sigma_above_baseline: 3.0
pre_pulse: 1
post_pulse: 5

# ROI stands for Region of Interest. Ex. Several variables (ex. max height, integral) are computed within ROI.
roi_start_ns: [-180, -20, 150]
roi_end_ns: [-100, 60, 4000]

# PulseFinder: scipy peak finding
pulse_finder_algo: 0
scipy_peak_finder_parameters:
  distance: 20
  threshold: 0.3
  height: 0.3 # None
  prominence: 1.0 #
spe_height_threshold: 0.125 # if a pulse-channel height is above this threshold, it's counted toward coincidence
